export class sharedConfig {
    public static EndPoint = {
      GetUserAccess: 'Cases/GetUserAccess',
      GetDynamicInputFormDetail:'DocProcessing/GetDynamicInputFormDetail',
      SaveDynamicInputFormDetail:'DocProcessing/SaveDynamicInputFormDetail',
      getBatchDetails: 'Cases/GetBatchCasesDetails',
      getTORLookups: 'DocProcessing/GetTORLookups',
      getTiffUrl: 'DocProcessing/GetFilePath',
      getPresignedTiffUrl: 'DocProcessing/GetPresignURLForFilePath',
      completeAuditForCase: 'DocProcessing/CompleteAuditForCase',
      updateRecordDetails: 'DocProcessing/SaveAndCompleteAuditForCase',
      archiveBatch: 'DocProcessing/ArchiveBatch',
      getAllCaseDetails: 'Cases/GetWorkQueueAllCases',
      reprocessBatch: 'DocProcessing/ReprocessBatch',
      BulkCompleteAuditForCases: 'DocProcessing/BulkCompleteAuditForCases',
      downloadBatch: 'v1/GetBatchCasesResults',
      abortBatch: 'DocProcessing/AbortBatch',
      GetGridMetadata:'DocProcessing/GetGridMetadata',
      getAssignReassignCasesLookups: 'Cases/GetCaseAssignee',
      updateBulkCaseAssignee: 'Cases/UpdateBulkCaseAssignee',
      getTaskDetails: 'Cases/GetTaskDetailsByCaseId',
      getVerifyVaersId: 'Cases/VerifyVaersId',
      bulkSaveDynamicDetail: 'DocProcessing/BulkSaveDynamicInputFormDetail',
      UpdateCaseBulkStatus: 'Cases/UpdateCaseBulkStatus',
      GetMatchedVaersData: 'Cases/GetMatchedVaersData',
      UpdateRecordReviewStatus: 'DocProcessing/UpdateRecordReviewStatus',
      GetGridData: 'DocProcessing/GetGridData',
      UploadSplittedFilesToOutputFolder:'DocProcessing/UploadSplittedFilesToOutputFolder',
      getLookupsForFilter:'Cases/GetWorkQueueFilterLookupValues',
      GetSummaryOutputDetails: 'Cases/GetSummaryOutputDetails',
      GenerateSummaryOutputDocument: 'Cases/GenerateSummaryOutputDocument',      
      getRecordDetails: 'DocProcessing/GetRecordDetails',
      GetCaseAuditTrailDetails: 'Cases/GetCaseAuditTrailDetails',
      DeleteCases: 'Cases/DeleteCases',
      GetAssignedRolesForUser: 'Cases/GetAssignedRolesForUser',
      GetTeamMemberDetails: 'Cases/GetTeamMemberDetails',
      SaveCaseAllocationAndTempAdminDetails: 'Cases/SaveCaseAllocationAndTempAdminDetails',
      GetCaseAllocationAndTempAdminDetails: 'Cases/GetCaseAllocationAndTempAdminDetails',
      GetCaseUntaggedPages: 'Cases/GetCaseUntaggedPages',
      GetCaseDislikedTorIdList: 'Cases/GetCaseDislikedTorIdList',
      getUserQueue: 'Cases/GetWorkQueueForUser',
      getWorkQueueFilterLookupValues: 'Cases/GetWorkQueueFilterLookupValues',
      GetloadWidgetData: 'Insights/GetDashboardDetails',
      getCaseDetailsValue: 'Cases/GetCasesDetails',
      getBatchDetailsValue: 'Cases/GetBatchDetails',
      assignMultipleTask: 'Cases/UpdateBulkTaskAssignee',
      updateBulkCasePriority: 'Cases/UpdateBulkCasePriority',
      assignMultipleCase: 'Cases/UpdateBulkCaseAssignee',
      GetCaseAssignee: 'Cases/GetCaseAssignee',
      InitiateFolderIntake: 'DocProcessing/InitiateFolderIntake',
      updateCaseStatus: 'Cases/UpdateCaseBulkStatus',
      newReprocessBatch: 'DocProcessing/ReprocessMemberDetails',
      getDynamicFieldDetailsForTOR: 'DocProcessing/GetDynamicFieldDetailsForTOR'
    };
  }
  